#!/usr/bin/env node

var walker = require('at-at');
var fs = require('fs');

process.chdir('./party/jspm/github/');
walker.walk('./', function(files) {
    // files is an array of filenames (including the paths).
    files.forEach(function(fileName, index, array) {
        if (fileName.match(/famous@.*/)) {
            if (!fileName.match(/famous@[\.0-9a-zA-Z]*\.js/) && fileName.match(/\.js$/) ) { // famous@* but not famous@*.js
                var fileContent = fs.readFileSync(fileName).toString();
                if ( fileContent.indexOf('"deps') === -1 ) {
                    console.log('Adding meta info for', fileName);
                    fileContent = fileContent.split("\n");
                    var filePosition = 0;
                    fileContent.splice(filePosition++, 0, '"deps ../core/famous.css!";');
                    fileContent.splice(filePosition++, 0, '"deps famous-polyfills";');
                    fs.writeFileSync(fileName, fileContent.join("\n"));
                }
            }
        }
    });
});
